### ISSUE TITLE
Denied Masquerade root access; now what?

### ISSUE THREAD

**Issue by seanspotatobusiness** [nicholaschum/substratum#102]
I randomly had a pop up asking me to grant Masquerade root access and I'd never heard of Masquerade so I denied root access. I searched and found a possible relationship to Substratum which I use. How can I grant Masquerade root access now? I'm not sure what app controls this/where to find this setting? I opened SuperSU because I thought that controlled this but it says that it has no stored app grants/denys  and furthermore it asked for root access itself so it presumably cannot be in control of root access.

**Comment by codebucketdev** [comment]
@seanspotatobusiness Never heard of Masquerade root, sounds kinda exotic 🤓

**Comment by Sykopompos** [comment]
Masquerade has been depreciated back in March and was replaced with theme interfacer and no longer needs root, I would suggest finding a more up to date rom build

**Comment by seanspotatobusiness** [comment]
Okay, thanks very much for this information; I'll update ASAP.
