### ISSUE TITLE
Add support for Samsung devices

### ISSUE THREAD

**Issue by gofirst2220** [nicholaschum/substratum#109]
See title. I'm on AT&T and some of their older devices like the S6 aren't root-able while the S7 is bootloader unlockable, but not sure about the S8 yet but I'm planning to buy S8 this winter.

Aside from that, I wanted to try out this theming engine on my S6 on Nova Launcher with Touchwiz as base framework but it still asks for root access.

My OS version is Nougat Beta 3 while AT&T haven't officially released the 7.0 to the S6 yet.

**Comment by msfjarvis** [comment]
@gofirst2220 It asks for root access because it needs root access. That isn't changing anywhere before you get on a custom ROM with rootless substratum support.

**Comment by Surge1223** [comment]
Someone finally topped beans' troll capitalization post.

**Comment by nathanchance** [comment]
This is not possible because we NEED elevated permissions to copy overlays to either /system or /data. With custom ROMs, we wrote our own sepolicy, framework modifications, and interface system; we can't do that on a stock ROM without root.

**Comment by gofirst2220** [comment]
Well, I'm not a troll but interested in substratum just curious tho.

**Comment by minz1** [comment]
@gofirst2220 no u
