### ISSUE TITLE
Permission to include into F-Droid

### ISSUE THREAD

**Issue by ghost** [nicholaschum/substratum#112]
Would it be accepted by the maintainer of this project to include Substratum in the F-Droid free software repository? I understand it is GPLv3 licensed, so in that aspect it should not be a problem.

But F-Droid requires that the maintainer of a project agrees to have it included into F-Droid.

On another side note, does Substratum require Google Play Services, if yes, why exactly?

**Comment by nathanchance** [comment]
@fredddii yes, it does due to Firebase integration, which we use for testing and getting bug reports. Due to this, I believe that excludes us from F-Droid; however, I have not looked into this much.

**Comment by codebam** [comment]
actually it's due to the bundled theme compiler

**Comment by codebam** [comment]
I tried getting it on fdroid a while back

**Comment by codebam** [comment]
to get it on fdroid you have to compile the compiler inline using android-ndk

**Comment by nathanchance** [comment]
https://gitlab.com/fdroid/rfp/issues/57

None of this has or will change unfortunately.

**Comment by codebam** [comment]
not to be a bother, but technically you're violating GPLv3

**Comment by LumenCeleste** [comment]
@codebam Nope they does not, the Google proprietaries are Apache License 2.0 licensed which is compatible with GPLv3 (I think one cause why Torvalds doesn't like v3).
To the NDK thing, these libraries/binaries are dynamically linked, that means no GPL violation, it would be different for static linked libraries/binaries.

**Comment by codebam** [comment]
there are statically linked libraries

**Comment by Surge1223** [comment]
Wait what? Yes they are statically linked, used the NDK, and only bionic  libc and ndks version of llvm libc++ that is statically linked.  It would be trivial to make it dynamic, and either way it is built inline, it can be built with the ndk out of tree as well, hell i built it on my phone with a bootstrap gcc i compiled against ndk (and only ndk, its not really a challenge to compile if you use glibc and dont have to deal with the limitations of how neutered bionic is ) but regardless

whatever way it needs to be compiled, is no issue. 

also we dont use any native libraries except for googles Firebase libs.

[aopt Android.mk](https://github.com/Surge1223/android_frameworks_base_aopt/blob/test5/Android.mk)


Still the statically linked and dynamically linked thing makes no sense, can you provide documentation, its literally a linker flag lol.

**Comment by codebam** [comment]
there are a few other binaries, but if they were compiled inline as well then I can't see why f-droid would decline it. it would have an anti-feature listed because of firebase and play services (since they do analytics I think?), but that's not really an issue

**Comment by dkanada** [comment]
I am pretty sure F-Droid does not accept play services in any form for their repository, technically that can be fixed with a build option that doesn't include play services. They accept third party libs from a list of trusted repos and do not allow binaries. I understand you guys don't plan on adding support for F-Droid, just wanted to provide a bit more information about their policies here.

While I am here, would you be open to someone else maintaining the F-Droid build option or possibly forking the project in some form to get the app added?

**Comment by Surge1223** [comment]
Well I was under the impression that f-droid.org was now closing? Did they find a new maintainer?

Anyways Substratum requires a binary that most oems don't ship with except for, surprisingly, Samsung. The binary can be made using stock aosp sources very easily. 

You could probably use studio to make it, granted you'd need to have these aosp repos:

frameworks/base/tools/aapt
frameworks/base/libs/androidfw
external/libpng
external/expat
system/core/libutils
system/core/libcutils
system/core/libziparchive
system/core/liblog 
system/core/base
bionic/libm
bionic/libc
external/libz
external/libc++

My git game is not strong, so I dont know if it's possible to grab subdirs from frameworks/base, system/core, or bionic without having to sync/clone/fork the entire repo. But if some git warrior out there knows how to do that, I will gladly write the Android.mk to make the binary build in android studio 

Subs is committed to being open source.
