### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by 0xFF600** [nicholaschum/substratum#119]
Would be great for those who don't use the PlayStore!

About: https://f-droid.org/
Submissions: https://gitlab.com/fdroid/rfp/issues

**Comment by anirudhgupta109** [comment]
@0xFF600 no thanks, i prefer Google Play

**Comment by nathanchance** [comment]
#55 and #112

**Comment by 0xFF600** [comment]
I should have searched the closed issues first. Thanks.

**Comment by 0xFF600** [comment]
The [f-droid submission location has changed to gitlab](https://gitlab.com/fdroid/rfp/issues), I would be willing to submit this on your behalf if you are OK with me doing so..?

apkmirror is untrustworthy and I've been unable to find an apk on xda.

**Comment by nathanchance** [comment]
@0xFF600 

1. We've already been [denied](https://gitlab.com/fdroid/rfp/issues/57) on F-Droid so I don't think another submission is going to change anything.

2. We can consider uploading a release APK here (as we have in the past).

**Comment by anirudhgupta109** [comment]
@nathanchance doesnt apk mirror already upload the Substratum apks? why not use that?

**Comment by nathanchance** [comment]
@anirudhgupta109 Yes but @0xFF600 doesn't trust them as he said. It would take next to no effort to upload them here.

**Comment by 0xFF600** [comment]
@nathanchance 

I should have also checked the closed submissions to see if it had been attempted already. Apologies and many thanks.

**Comment by nathanchance** [comment]
@0xFF600 it's been brought up before internally but never publicly so you are good. I'll bring it up and see if we can make it more consistent than it has been before.

https://github.com/substratum/substratum/releases

**Comment by dimqua** [comment]
Please still consider to provide fully open-source [build flavor](https://developer.android.com/studio/build/build-variants.html) for F-Droid needs (if it possible), then F-Droid maintainers will be happy to include your app.

**Comment by msfjarvis** [comment]
@dimqua we'll be releasing signed builds from our server on every release beginning the next one so that should address the concern of people who do not use Google Play. Substratum is and will always be a fully open source community project. All builds from official sources are built from our release branch.
