### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by nathanchance** [nicholaschum/substratum#120]
- [ ] AppCrashReceiver needs framework awareness (in progress @MSF-Jarvis)
- [ ] Check WeakReferences for NULL values
- [ ] Hero images are occasionally incorrect

**Comment by anirudhgupta109** [comment]
@nathanchance also the Substratum crash bug introduced when the substratum is updated with applied overlays to it

**Comment by msfjarvis** [comment]
> @nathanchance also the Substratum crash bug introduced when the substratum is updated with applied overlays to it.

Isn't specific to substratum, practically it can happen to every single app. Use the "Automatically update theme overlays" and "Automatically update target overlays" options which were introduced for this very specific use case

**Comment by nathanchance** [comment]
Moved to projects: https://github.com/substratum/substratum/projects/2
