### ISSUE TITLE
Got stuck in a boot loop

### ISSUE THREAD

**Issue by thopiekar** [nicholaschum/substratum#122]
Hey,

I'll make it short and try to provided the most details possible.

I'm using LineageOS 14.1 on my Motorola X Play (lux) and installed substratum via Play Store.
Also I installed this theme (https://play.google.com/store/apps/details?id=substratum.greyce.pc) and did the following.
After opening you app, I chose this theme and used my phone for 1-2 days regularly. After that I found another theme and wanted to apply this one.
Before doing this a uninstalled all overlays and apps began to crash so I restarted my phone.
Then I got stuck in a boot loop.

Instead of blaming you guys, I'd like to provide additional info and help out to fix that. Therefore I began to enable adb rooted via TWRP.
It took a long time, but I'm sure it is useful to understand the issue here and for you handier to improve your app.

So what I notice from the logcat, is, that (probably ART) is still looking for the apk with the overlays inside.
You can find the logcat of the loop here: http://pastebin.com/7B0KFUgX

So the question is: What happend over here? Is the file available somewhere else, so I can copy or symlink it to the location, where ART expects it?

**Comment by msfjarvis** [comment]
Your link is 404'ing so I can't really see what happened there and will simply have to go by your rather surprisingly detailed research (thanks for that, it's appreciated). The system is most probably looking for idmap files. For that you would like to get rid of `/data/resource-cache/` which the `SubstratumRescue_Legacy` zip in `/sdcard/substratum/` already wipes. Try flashing the ZIP and get back.

**Comment by thopiekar** [comment]
@MSF-Jarvis I updated the link. I had to copy the URL from one (where I have ADB installed) to another device, where I'm still logged in into GitHub.
Just refresh the page 😉

**Comment by KreAch3R** [comment]
@MSF-Jarvis alternative link: https://hastebin.com/osesaqosug.vbs

@thopiekar Thanks for the thoughtful bug report. Help me help you with a couple of questions:
* Did you fix the bootloop? if not, how?
* LOS official or modified? LOS with OMS? Was Substratum working in legacy mode?
* Do the apps regularly crash after uninstalling or is that happening with this specific theme
* Can you replicate every time?
* Can you replicate with another theme?
* Where in the logcat do you think what you're describing is happening? I see a lot of lines of de/odexing work, but not sure I'm seeing what you describing.

**Comment by thopiekar** [comment]
@KreAch3R 
 - No I couldn't fix it. That's why I'm asking here for help - I'm not familiar with what is going on behind the scenes of the overlay stuff.
 - LOS official, but can't remember which build. What is OMS? A special feature? Well in that case I use the normal build. (So therefore the legacy mode I guess?)
 - Couldn't test that. I'm still stuck in the loop here.
 - Same here..
 - Same here..
 - Well, during boot it is I guess trying to compile all the apps, because I wiped the ART cache and the normal cache. However, after this it is crashing, because it can't find a file (the mentioned IO Error...).

Here is an example:
```
07-27 14:59:53.037 16912 16912 W         : Unable to open '/vendor/overlay/android.GreyceSubstratum.apk': No such file or directory
07-27 14:59:53.037 16912 16912 W zipro   : Error opening archive /vendor/overlay/android.GreyceSubstratum.apk: I/O Error
07-27 14:59:53.037 16912 16912 D asset   : failed to open Zip archive '/vendor/overlay/android.GreyceSubstratum.apk'
```

**Comment by msfjarvis** [comment]
@thopiekar what method did you use to uninstall overlays? Substratum, Settings or the Rescue zip?

**Comment by thopiekar** [comment]
@MSF-Jarvis Your app and afterwards I tried it with your *Rescue.zip
Btw. am I using the legacy mode? Sorry, that I ask these boring questions.

**Comment by msfjarvis** [comment]
On Lineage official builds yes you will be using the legacy mode of substratum. Also since you asked about OMS in your reply to George, it's the framework additions from Sony and improved upon by the team, that let us apply themes on the fly without needing reboots as in legacy mode.

**Comment by thopiekar** [comment]
@MSF-Jarvis Thank you for the explanation 👍 
Therefore using the *RescueLegacy.zip should make my phone work again?

**Comment by msfjarvis** [comment]
If I'm on the correct track on your issue then yes it should.

**Comment by thopiekar** [comment]
Worked! Awesome work guys!
