### ISSUE TITLE
Cast to BitmapDrawable is dangerous

### ISSUE THREAD

**Issue by maxwen** [nicholaschum/substratum#124]
App icons can be more then BitmapDrawables e.g. VectorDrawable or even ShapeDrawable
Using such an app icon in a theme causes instant crash on install or change here
https://github.com/substratum/substratum/blob/dev/app/src/main/java/projekt/substratum/services/packages/PackageModificationDetector.java#L176
Easiest is to convert to BitmapDrawable if needed

**Comment by nicholaschum** [comment]
Ah, you're correct @maxwen, thanks for looking out! :)
