### ISSUE TITLE
Auto-disable variants if another variant is installed

### ISSUE THREAD

**Issue by boswelja** [nicholaschum/substratum#125]
I recently had one of my friends being confused by the color variants in my theme, he wasn't disabling any of the previous colors. So my suggestion is, what if we auto-disable other variants when a new variant is applied? I can try implement this if I get the go ahead, but I wanted to discuss how it would work (e.g. making it theme-specific)

**Comment by nicholaschum** [comment]
@boswelja sorry for the heavily delayed response, but you are free to do it as long as there are no regressions. As usual, dev branch so we can have testers on it. Thanks!

**Comment by ghost** [comment]
Switching between colour variants usually works on OMS roms. On legacy however it is a mess. Only one overlay can remain active on legacy causing inter as well as intra-theme issues.

Let's say there are two themes X and Y
User has applied X theme with overlay com.android.settings with some option selected. Unless this overlay is uninstalled:
- any other option from theme X for com.android.settings cannot be applied
- the overlay com.android.settings from theme Y will not be applied.

Just to be clear, overlays will be installed. The user won't see any changes unless the first overlay is removed.

What I suggest is whenever com.android.settings (or any other overlay) from any theme is installed, all the other com.android.settings overlay from the same theme as well as other themes should get disabled. This is however needed in legacy mode only. With oreo around the corner, I'm not sure if this will be worth the effort though. Cheers

**Comment by boswelja** [comment]
@ungeeked so basically disable all other overlays for a specific package in legacy mode?

**Comment by boswelja** [comment]
@nicholaschum no worries, it gives me something to try over the weekend!

**Comment by boswelja** [comment]
also is there a need to make this optional? I can't think of any themes that make use of separate overlays for the same package

**Comment by ghost** [comment]
@boswelja Yes. All other overlays that are already installed for to the same app.

**Comment by boswelja** [comment]
@ungeeked that one will definitely have to be optional, otherwise you wouldn't be able to combine themes cx

**Comment by ghost** [comment]
Optional is alright as it is only needed in legacy. Maybe make it auto enable in legacy. I don't think we can mix themes in legacy mode anyway.

**Comment by boswelja** [comment]
@nicholaschum How should I go about testing if my debug subs builds won't connect to Andromeda?

**Comment by msfjarvis** [comment]
@boswelja Tap the connected card in Andromeda 8 times.

**Comment by boswelja** [comment]
ah, ty

**Comment by boswelja** [comment]
Resolved after merging #149, not sure why it didn't auto-close
