### ISSUE TITLE
Cannot apply any boot animation

### ISSUE THREAD

**Issue by maple3142** [nicholaschum/substratum#130]
I am using Resurrection Remix 7.1.2 on Redmi Note 4(mido).

Everything except boot animation in substratum work perfectly.

But I cannot apply any boot animation, it always say because device is encrypted so require root to apply.
But it still doesn't work with root permission

**Comment by msfjarvis** [comment]
A logcat will go a long way

**Comment by maple3142** [comment]
It works now.
