### ISSUE TITLE
[Suggestion] Applying Font Pack to Android Oreo if device rooted

### ISSUE THREAD

**Issue by Sparker0i** [nicholaschum/substratum#135]
The current Andromeda+Substratum combination allows a great number of customization, starting from SystemUI all the way upto Individual apps. But sadly there are more things that the standalone Substratum app can do, while the combination can't, like applying universal system wide font.

My proposal is to allow having to utilize those features in Android Oreo, by checking if the system is rooted or not. If yes, the main Substratum app can install the system wide font and boot animations in Legacy mode, else the app won't show such options at all.

**Comment by msfjarvis** [comment]
@Sparker0i We're not big on modifying system partition when not required to. Sorry, not happening. Legacy on nougat didn't support font application either.

**Comment by Sykopompos** [comment]
@Sparker0i But why? Andromeda isn't meant for rooted phones, regular subs is

**Comment by PDesire** [comment]
@MSF-Jarvis Somewhere fears SafetyNet

**Comment by MSF-Jarvis** [comment]
@PDesire more like I hate root code but whatever floats your boat

**Comment by Sykopompos** [comment]
@MSF-Jarvis Why you quote the bot?

**Comment by anirudhgupta109** [comment]
@Sykopompos Cause he can?

**Comment by PDesire** [comment]
@anirudhgupta109 Ok this went too far :D

**Comment by Sykopompos** [comment]
@anirudhgupta109 Happy birthday in advance @GreekDragon.

**Comment by Sparker0i** [comment]
@Sykopompos Custom ROMs.

**Comment by Sykopompos** [comment]
@Sparker0i

**Comment by krypticallusion** [comment]
@anirudhgupta109 Stop spamming, why do you even have a GitHub account :3

**Comment by nathanchance** [comment]
Stop replying to GitHub comments unless you are commenting on the technical discussion at hand. I'll start blocking people from commenting on these issues.

**Comment by krypticallusion** [comment]
@krypticallusion ^

**Comment by Sykopompos** [comment]
I'm still a bit lost on why would we add root font code to Andromeda when it is meant  for stock ROMs without root though.

If we would add it anywhere it would be regular subs because rooted people would be upset that you need to buy Andromeda to change fonts then
