### ISSUE TITLE
Andromeda screen constantly showing up

### ISSUE THREAD

**Issue by snacdaws** [nicholaschum/substratum#140]
The Andromeda screen stays up even when rooted and there is no way to dismiss it

**Comment by snacdaws** [comment]
*** on version 853

**Comment by Sykopompos** [comment]
Clear substratum app data, should force the root prompt to come up

**Comment by snacdaws** [comment]
Thing is that it shows up after the root prompt(freshly installed substratum after re-rooting after I had to factory reset) 

Installed 843 and it works perfectly fine so something has changed from 843 to 853(something to do with Andromeda within substratum)

**Comment by snacdaws** [comment]
Just updated from 843 via play store and didn't have same issue, only seems to happen when it is a fresh install of substratum
