### ISSUE TITLE
Connect to Andromeda shows when launched from script without opening before

### ISSUE THREAD

**Issue by Sparker0i** [nicholaschum/substratum#145]
This seems to be a bug. When we install the Andromeda and Substratum apps (and dont open either) , and then run the script, it opens the Substratum app, showing tutorial and then showing the message to connect to Andromeda first.

**Comment by Surge1223** [comment]
Yeah, at that point is the Andromeda status green? If you just run the script again it should work. Its a known issue being worked on.

**Comment by Sparker0i** [comment]
Yes it is green. Thanks for letting the status known

**Comment by nicholaschum** [comment]
@Sparker0i can you confirm that if you're running play store or github/test builds?

The message of connection to Andromeda is not cached or saved, it's all live.

**Comment by Sparker0i** [comment]
Downloaded substratum from play store and using it ever since

**Comment by nicholaschum** [comment]
@Sparker0i can you record yourself launching the AndromedaClient on your desktop to see what the issue you are facing? I am not sure I quite understand what's going on

**Comment by Sparker0i** [comment]
Sure will do in a few hours. But just wanted to say this happens only on
launching for the first time, subsequent launches do not have this problem.

**Comment by Sparker0i** [comment]
https://youtu.be/FQuAjPR_PD8

**Comment by Surge1223** [comment]
Yep. Same bug, working on it.
