### ISSUE TITLE
Use AOPT if the ROM is marked "supported"

### ISSUE THREAD

**Issue by arter97** [nicholaschum/substratum#147]
Last time I asked why AOPT is hidden and unused, the answer I got was "some manufacturer stock ROMs were problematic with it."

Since AOPT is where all the custom AAPT improvements are at, we should enable it if the ROM supports it.

We should make supported ROMs check more useful, extending it to enable AOPT.
Can we refactor checkFirmwareSupport() from app/src/main/java/projekt/substratum/common/Systems.java to enable AOPT?

**Comment by Surge1223** [comment]
IMHO this isn't an issue more of a suggestion, PR's are welcome

**Comment by arter97** [comment]
So everyone's ok with this behavior change?

**Comment by nicholaschum** [comment]
Yes sir!
