### ISSUE TITLE
Can't find substratum rescue zip

### ISSUE THREAD

**Issue by rehannali** [nicholaschum/substratum#156]
Hi! I'm stuck in boot loop after installing overlay on my OnePlus 5. I'm unable to find substratum rescue zip in substratum folder to remove the overlay. I'm using oxygen os. 
Is there any other way to uninstall overlays or where can I find rescue zip?
Thanks.

**Comment by msfjarvis** [comment]
https://androidfilehost.com/?fid=889764386195921122 should do it. Also, please refrain from using the GitHub issues section for user support, our Google+ Community and XDA Subforum are for that purpose.
