### ISSUE TITLE
APK Builds Stopped?

### ISSUE THREAD

**Issue by 542d2ad116** [nicholaschum/substratum#157]
Have apk build locations changed? Cant find any since build 822.

Issue #119 specifies the following locations:

http://download.projektsubstratum.com/APKs/
https://github.com/substratum/substratum/releases/

Thanks.

**Comment by 542d2ad116** [comment]
Also,

Whatever came of this?



@dimqua  

> we'll be releasing signed builds from our server on every release  beginning the next one

 so that should address the concern of people who  do not use Google Play. Substratum is and will always be a fully open  source community project. All builds from official sources are built  from our release branch.
--

**Comment by YechiamW3** [comment]
Idk about you but it appears right there quite clearly, latest is 911.

**Comment by 542d2ad116** [comment]
I'm not talking about the source zip or tar.gz downloads. I'm referring to the pre-built apk files. Looking on the[ releases page](https://github.com/substratum/substratum/releases/) there is a link to the apk for build 822, but not for build 852 or above. 

The last build I can see on http://download.projektsubstratum.com/APKs/
is also 822.



See attached screenshots.
![screenshot](https://user-images.githubusercontent.com/33497526/32574503-4f2c7876-c4c9-11e7-9cdf-94ad24b2a1f8.png)
![screenshot2](https://user-images.githubusercontent.com/33497526/32574510-53d12b2e-c4c9-11e7-8fec-23381e415026.png)

**Comment by dimqua** [comment]
But the latest version on Play Store is 914.

The source code of v912 is available: https://github.com/substratum/substratum/archive/912.zip

**Comment by nathanchance** [comment]
I will try to remember to start these up again when we do our next public release.

**Comment by msfjarvis** [comment]
@542d2ad116 the 915 APK is uploaded to GitHub releases at https://github.com/substratum/substratum/releases/tag/v915. All further releases will also be simultaneously uploaded to GitHub and play store henceforth

**Comment by IzzySoft** [comment]
Looks like release 1021 misses the APK again.
