### ISSUE TITLE
Please add Magisk / Systemless support

### ISSUE THREAD

**Issue by bubundas17** [nicholaschum/substratum#159]
Please add systemless/Magisk supposed in it. I don't want to break saftynet on my phone! 

I found a module on xda forms but it is no longer working with latest Magisk. Do something about it!

**Comment by msfjarvis** [comment]
Are you actually asking us to fix and provide support for something that has nothing to do with us? Ask the module author to fix it.

**Comment by bubundas17** [comment]
Nope, Actually I am asking you to add support for Magisk. Instead of directly writing in /system

**Comment by msfjarvis** [comment]
You already said there's a magisk module, fix it and use it. There are no immediate plans to upstream it into Substratum.

**Comment by bubundas17** [comment]
I am not asking you to fix someone else module. I am asking to add systemless Magisk support officially.

**Comment by msfjarvis** [comment]
You are not reading my replies at all. Nothing related to magisk is coming into Substratum anytime soon. If you need rootless and safetynet and whatever, your best bet is to simply stop using Substratum or get your Magisk module fixed. We have no immediate plans for this.

**Comment by bubundas17** [comment]
Don't be rude dude! Okk I got your point! 
By the way I really appreciate your work, Thanks for the great theme engine!  I use it at daily basis on my phone. But as it brakes saftynet I am unable to use banking apps!  Thanks for your quick response!

**Comment by divadsn** [comment]
@bubundas17 How about using a ROM with OMS built-in when you're already using Magisk?

**Comment by bubundas17** [comment]
Well, I Am using MI A1. it is a Android One Device it should receive Oreo via OTA update in few days.

It would enable OMS support for substratum. 

But I am asking it for our users. I think there were many other people who are looking for substratum systemless support.

**Comment by bubundas17** [comment]
@divadsn are you there ?

**Comment by divadsn** [comment]
@bubundas17 No, I'm afk.
