### ISSUE TITLE
Build overlay failed on Substratum v931 (Android 7.1.2)

### ISSUE THREAD

**Issue by Saylance** [nicholaschum/substratum#162]
» [$package_name$]: new_alloc_size overflow
» [$package_name$]: Installation of "com.aicp.aicpota" has failed.
>>>> and same for all another 100500 packages <<<<

Triggered assert here:
https://github.com/LineageOS/android_system_core/blob/cm-14.1/libutils/VectorImpl.cpp#L407

safe_mul code:
https://github.com/aosp-mirror/platform_external_safe-iop/blob/master/include/safe_iop.h#L207

Android 7.1.2 (Ressurection Remix 5.8.5) << full OMS support.
Looks like AAPT from Oreo, cause this.

Maybe use AAPT2, or any workaround to avoid overflow, or return back AOPT for Android 7.1.2 users.

**Comment by nathanchance** [comment]
This has been fixed as of 66346b3cd4872199d752560721f971a08f0f65e7, upgrade to 950+
