### ISSUE TITLE
Auto-update solution needed for legacy mode users

### ISSUE THREAD

**Issue by blackwind** [nicholaschum/substratum#164]
Using Substratum in legacy mode, you pretty much have to disable automatic updates in the Play Store, lest you end up with force closes when you need to open an app the most. For those running flagships with the latest processors and no encryption, I guess that's not such a big deal, as you're never more than a five-second reboot away from getting back to business; for those of us running older phones *with* encryption, though, a five-*minute* reboot when I absolutely need to open my Gmail *right now* is devastating.

I understand that it's not possible to auto-update overlays on-the-fly in legacy mode, and I also understand that legacy mode isn't a priority, but could we get a setting to auto-update overlays in the background (which would, of course, still require a reboot afterwards, but at least it'd be automatic, and at least I'd get a notification about it), or, at the very least, a notification on app updates that this app is probably broken now and that I should apply the latest version of my theme? As is, I'm experiencing far too many unfortunate surprises when I'm on the road, and disabling automatic updates in the Play Store is an extremely frustrating workaround for a number of reasons.

**Comment by Sykopompos** [comment]
The problem with Auto updating an overlay without the reboot is that there is a good chance that it would just cause the app you just updated to crash anyways until you reboot because resources can't be updated till then

**Comment by blackwind** [comment]
Right, but if the choice is between me knowing that immediately because I got a notification or suddenly getting screwed at the worst possible moment, I'll gladly take the former.

**Comment by nicholaschum** [comment]
Auto-updating an overlay on legacy will not do anything to help you. As this is legacy, we can't even capture the crashes of other apps so we can't inform the user.

As idmap only occurs after a reboot, a constant dialog telling you that an app has stopped should be enough to know an overlay needs to be updated/unloaded, especially for legacy, which, as the first boot states, is provided "As-is"
