### ISSUE TITLE
Build & Enabling overlays gets stuck on S9

### ISSUE THREAD

**Issue by PerLycke** [nicholaschum/substratum#165]
Building & Enabling a larger amount of overlays (60+) on the S9 makes the building process freeze, and eventually it'll get stuck on "Preparing theme overlay..." for an overlay. This is not overlay specific, it's more like the process is 'slowing down' and finally just gets stuck.

I grabbed this logcat when it got stuck on com.android.systemui.tiles.SwiftforSamsung.Dark

https://gist.github.com/PerLycke/cec64ee59bc91247ffc35d6eaad275b4

Contact me if you need more info or additional logs

**Comment by nicholaschum** [comment]
The log is inconclusive. Please grab us another one with SubstratumLogger and SubstratumBuilder filters if possible.

**Comment by PerLycke** [comment]
It happened twice, grabbed that log the second time. On my attempt to reproduce a third time to grab a SubstratumLogger/Builder log, Andromeda started disconnecting and Subs crashing

Firmware: ARB1
Subs version: Ci / 960

Log when that happened: https://gist.github.com/PerLycke/bd539e4f61b196895ae6f96376d034fc

I'll record a new log with OP issue next time it occurs

**Comment by nicholaschum** [comment]
Was there any news regarding this? I've read that some S9's work perfectly

**Comment by PerLycke** [comment]
No, no news. It's been working since latest ARC4 firmware version

**Comment by nicholaschum** [comment]
So it's working again?

**Comment by PerLycke** [comment]
Yes, haven't happened since the latest firmware update ARB1 -> ARC4. You can close this

**Comment by nicholaschum** [comment]
Good to hear, thanks!
