### ISSUE TITLE
There needs to be a way to update automatically

### ISSUE THREAD

**Issue by Kommynct** [nicholaschum/substratum#168]
Could there please be a button to update anything with just the yellow "update available" text?

I don't use all of the overlays in any of my themes, and i mix and match, as is, i have to manually select every single one, and its horrid.

Please help thank you for your time.

**Comment by nicholaschum** [comment]
Have you tried the automation functions within our Settings portion of the app?

If you are on Rootless OMS/Subs, then you are able to utilize these automated functions to automatically update a theme's "orange" overlays when the theme is updated, or even automatically recompile the overlays when the target app (e.g. Instagram) is updated.

**Comment by Kommynct** [comment]
I have tried them, I find substratum frequently locks up when I let it run in the background, which I suppose is a separate issue altogether. However, I haven't retried this feature in a long time, and totally forgot about it, so, thank you for that recommendation. However I do still believe a feature to select all yellow updated things would be useful. For example, I could disable all active overlays and then later re enable them without as much work.

Again, thank you for listening.
