### ISSUE TITLE
A way to find if there's already an overlay installed?

### ISSUE THREAD

**Issue by Volckius** [nicholaschum/substratum#169]
(Sorry if the titles a bit confusing, I'm not sure how to phrase it)

Can we get a way to find out if something already has an overlay from a different theme installed without going to the manager to check it every time? I'm not sure if they have that feature on root but I think it would be handy. For example,

Say I'm about to install a Chrome overlay, but I don't know if I already have an overlay for chrome installed from a different theme already. Can we get a way to know whilst were still in a themes menu? Like maybe a dialog box that states that there's already an overlay from a different theme installed on the device, and that it could make an error with the app. 

Thank you for your help!

**Comment by msfjarvis** [comment]
That's unnecessary complication, bad UX, as well as against the ability of Substratum to have multiple overlays on the same target package.

**Comment by Volckius** [comment]
@MSF-Jarvis oh alright, I didn't mean to block having multiple overlays allowed but just a heads up so when people would be installing a bunch of overlays at the same time that they don't have to manually check each time for say a light theme installed on the same app you want a black theme. Just thought it would be handy that's all.

Thanks for the answer anyways.

**Comment by Volckius** [comment]
@MSF-Jarvis oh alright, I didn't mean to block having multiple overlays allowed but just a heads up so when people would be installing a bunch of overlays at the same time that they don't have to manually check each time for say a light theme installed on the same app you want a black theme. Just thought it would be handy that's all.

Thanks for the answer anyways.
