### ISSUE TITLE
Freeze on Xperia X

### ISSUE THREAD

**Issue by therealxtrem** [nicholaschum/substratum#170]
I connected it to Andromeda and it stucks on all themes. When i go to "build and install", everytime it gets to call or play services it Freezes and the Installation bar stucks.

**Comment by nicholaschum** [comment]
This seems to be a system issue rather than our issue. If anything, substratum and andromeda doesn't affect anything system-related.

**Comment by therealxtrem** [comment]
Is there something i can do about it?

**Comment by nicholaschum** [comment]
As you said you are on an Xperia X device. These devices do not allow overlays from third parties to be installed. So this may require a rooted solution.
