### ISSUE TITLE
Add filtering by state to manager

### ISSUE THREAD

**Issue by myfrom** [nicholaschum/substratum#171]
Currently in the manager tab in Substratum app you can choose two sorting modes (which also isn't clear the first time you try Substratum, but that's not the point here).
I'd suggest to **add a way to sort or filter by state (enabled, disabled)** .

_How would it help user?_  
It would allow for even easier finding which overlays are disabled.
For example: You have a lot of themed apps and one just updated and it broke the overlay. In this case Substratum will turn off faulty overlay. When you update the theme the app is probably fixed but you have to scan the whole list for that disabled theme or alternatively enable all of the overlays which isn't ideal solution.

_Possible implementation_  
I'd suggest to remove the 'sort by' toggle and move this and filter functionality to a right drawer. It would be in line with Material Design guidelines and allow for further expandability later on.

**Comment by msfjarvis** [comment]
Just a passing remark for now: Your suggested implementation will look like crap and isn't really ideal with Manager being a fragment not an activity. What I would have, if we choose to implement this, is a dialog with sorting/filtering options in the form of grouped radio buttons.


PS: This comment is not to dismiss the feature request, but to suggest a more viable implementation should we choose to have this in substratum.

**Comment by nicholaschum** [comment]
I like the idea of showing what is enabled or disabled in the manager. But remember we also have a hidden mode to hide the disabled overlays from the manager if you wanted all enabled overlays to show up

**Comment by myfrom** [comment]
That's cool, didn't know about that. But it doesn't really solve the problem of filtering. You can only hide disabled ones, what if you want to see only disabled ones? Also, where can you toggle that? I can't find that hidden mode.

**Comment by Aekkapong18** [comment]
Ok good
