### ISSUE TITLE
crowdin project has been 502 ERROR

### ISSUE THREAD

**Issue by BiliCover** [nicholaschum/substratum#178]
crowdin project has been 502 ERROR
please fix it!
http://translate.projektsubstratum.com

**Comment by bohrabhijeet** [comment]
@BiliCover For now, use this link - crwd.in/substratum 
In the meantime I'll let the devs know about your issue.

**Comment by BiliCover** [comment]
@abhijeetbohra Can i translate Play store Introduction?


![screenshot](https://user-images.githubusercontent.com/34672832/44768061-a2d14a00-ab92-11e8-8108-a0c4e9e08c97.jpg)

**Comment by bohrabhijeet** [comment]
@BiliCover Feel free. 👍🏻

**Comment by BiliCover** [comment]
@abhijeetbohra but, where can i translate? i cant find in Crowdin.

**Comment by bohrabhijeet** [comment]
@BiliCover PS listing is not on Crowdin. And currently I don't think we need a Mandarin (or any other) language's translation. I'll let you know once it's needed.
