### ISSUE TITLE
Error when building with ci/all.sh

### ISSUE THREAD

**Issue by coolblock** [nicholaschum/substratum#179]
cargo test --release -- --nocapture
+ cargo test --release -- --nocapture
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: lib.cargo-bundle
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: package.copyright
warning: unused manifest key: lib.cargo-bundle
warning: unused manifest key: package.copyright
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro` (never executed)

Caused by:
  No such file or directory (os error 2)
---------------------------------

Not sure what I am doing wrong.
I am in fact building as root, not sure if that causes the problem.

ubuntu 16

**Comment by msfjarvis** [comment]
Well for one you're definitely building the completely wrong project for the place you've started the issue at. Double check before you spam places.
