### ISSUE TITLE
Substratum themes not loading

### ISSUE THREAD

**Issue by saboooor** [nicholaschum/substratum#181]
![Screenshot](https://i.imgur.com/OvnD2ON.jpg)

**Comment by bohrabhijeet** [comment]
@587saboor Did you try clearing the data of substratum? Are you on the latest version of substratum?

**Comment by saboooor** [comment]
@abhijeetbohra yes and yes

**Comment by bohrabhijeet** [comment]
@587saboor If you're rooted, did you grant root?

**Comment by saboooor** [comment]
@abhijeetbohra oh **** thanks
