### ISSUE TITLE
When scrolling, if you start your scroll gesture from a drop down menu, there is no delay, so instead of scrolling the whole page, it opens the drop down menu.

### ISSUE THREAD

**Issue by abqnm** [nicholaschum/substratum#182]
Normally the expected behavior is to scroll the entire page when dragging your finger in a scrolling gesture, regardless of the starting point of that gesture. But in the theme options page, if the starting point of the scroll gesture is on top of a drop down menu, it opens that menu and scrolls within it. 

This makes it very easy to inadvertently change theme options, and difficult to scroll, since there are only very tiny spaces between each section in the theme options page. The majority of it is comprised of drop down menus.

Can a slight delay be implemented to determine if the user is scrolling and have it scroll the page, and not open and scroll the drop down menu that happens to be located at the point of origin of the scroll gesture? It would greatly improve usability.

Thanks! 

Substratum version 1007
Android Version 8.0.0 (OCXS27.109-51-7)
Moto Z2 Force (Nash) / No Root / Dynamic OMS / Andromeda v22

**Comment by msfjarvis** [comment]
The behaviour is completely intentional and has been inherited from the Android framework, if you need a change, the right place to contact is the Google issue tracker at https://issuetracker.google.com

**Comment by abqnm** [comment]
Amusingly, yours is the only app I've used in the last 5 years that does this out of thousands of apps. 

So I guess literally every single other android developer has worked around this "intentional" flaw in creating their apps, but you'd rather keep the bad UX and hang the blame on Google, and not fix it for your app? Or it's not really a framework problem, and you're just deflecting...?

Don't blame it on a framework issue when you can easily solve it. It's only the Substratum app with this issue. Admit you just don't want to fix it or care. Don't blame it on Google that your app is poorly laid out and doesn't scroll properly. If the fault was on Google, every app with drop down boxes would behave this way. But they don't. So either every other developer fixes the supposed issue so it doesn't result in a bad UX, or there is no framework issue at all and you just don't care. 

Either way, why not just fix your app? Blaming Google because you don't want to fix the terrible UX is a shady way to handle this.

**Comment by msfjarvis** [comment]
Every app ever expands the drop down preference when you scroll from exactly on top of it, you simply haven't noticed that yet. Try scrolling from the overflow menu in any app, that's the exact same behaviour. Substratum is one of the few apps where you'd find multiple drop down lists arranged in such a tight fashion hence your assumption that it doesn't happen anywhere else.

**Comment by gargakshit** [comment]
@abqnm 😂

**Comment by Maxr1998** [comment]
@MSF-Jarvis
