### ISSUE TITLE
Problem with theme banner 

### ISSUE THREAD

**Issue by Darkcast** [nicholaschum/substratum#186]
The application doesn't display any theme banner and everything is washed out by the yellow background color.
![screenshot_20181202-202633](https://user-images.githubusercontent.com/1676655/49348123-910bb100-f671-11e8-9a35-74236ec02a58.png)
![screenshot_20181202-202902](https://user-images.githubusercontent.com/1676655/49348133-9f59cd00-f671-11e8-902e-278653a0d2e8.png)
I have cleared out the cache and the storage I also have rebooted

**Comment by djdarkknight96** [comment]
1. This isn't the place for this. 
2. It's not a bug...Uninstall lucky patcher FULLY for any support!

**Comment by msfjarvis** [comment]
Don't pirate things and all will be well again.
