### ISSUE TITLE
Overlays Not Installing on N9 Pie beta with Root

### ISSUE THREAD

**Issue by Leeeumm** [nicholaschum/substratum#188]
I am facing an issue where i am trying to install overlays for 3rd party apps since Samsung apps aren't themable on Pie but i try to install overlays then reboot and it says no overlays installed even though app says overlays are updated without any errors

**Comment by msfjarvis** [comment]
I'm not super familiar with Android P operation on Samsung devices so you're better off joining the Samsung support chat on Telegram (https://t.me/substratum) where you'll find OneUI users who're better suited to assist you.
