### ISSUE TITLE
substratum issue with magisk

### ISSUE THREAD

**Issue by juvevood** [nicholaschum/substratum#190]
1.Using substratum root mode
2.magisk version: 18.0 and manager:6.10
3.build any theme
I found that there were substratum modules in the module.and NFC crashed with pie.
After I downgraded to 1006 with magisk 17.3, everything worked.

**Comment by msfjarvis** [comment]
I don't understand a word in this issue and it deeply agitates me. There's no substratum modules in the module, there's overlays in the module which is precisely it's entire purpose. NFC crashing has nothing to do with the app, if the theme is causing the NFC app to crash, uninstall the overlay and report the same to the themer with the necessary information (which I'd like to point out, is sparse in this issue). Closing as invalid unless you can explain an actual issue.

**Comment by juvevood** [comment]
only "build/update" can cause this problem, so it's not relevant to the theme application.I think this problem has something to do with the magisk module of substratum , because the old version does not have the magisk module of substratum, and it works well. I don't understand why this module is added.Thanks!

**Comment by skittles9823** [comment]
@juvevood The module is added because magisk changed paths with magisk 18 and this is a better solution then directly placing the APKs into system/app

**Comment by argraur** [comment]
@juvevood @juvevood logcat of NFC crash or didn't happen

**Comment by juvevood** [comment]
@skittles9823 got it, thx. but this change caused my NFC to break down indefinitely

**Comment by msfjarvis** [comment]
> only "build/update" can cause this problem, so it's not relevant to the theme application.

Build and update _installs_ the theme so yes it's still a theme problem.

> I think this problem has something to do with the magisk module of substratum , because the old version does not have the magisk module of substratum, and it works well. I don't understand why this module is added.Thanks!

No it does not.

**Comment by 4PERTURE** [comment]
@juvevood Pretty sure the NFC crash has 0 to do with substratum's magisk module but ok

**Comment by juvevood** [comment]
@MSF-Jarvis I found that after installing a copy of the overlay layer under /sbin/.magisk/img/substrarum/system/ app to /sbin/.magisk/mirror/system/app, everything was fine again.  WHY?

**Comment by msfjarvis** [comment]
> @MSF-Jarvis I found that after installing a copy of the overlay layer under /sbin/.magisk/img/substrarum/system/ app to /sbin/.magisk/mirror/system/app, everything was fine again. WHY?

Because you moved the overlay from the Magisk module which you very likely disabled directly to your system partition?

**Comment by nakedpwr** [comment]
There does seem to be a great deal of learned experience on both sides. this was poorly taken care of though. And it was poorly taken care of publicly. Although I'm definitely not new to computers and I've even been in two wars and raised three children... I've been married more than once... 17 years working in surgery specializing in abdominal surgery - none of that means anything about Android. But what ive learned through all that experience is you promote in public and punish in private. I would be afraid of bringing any problem forward. I mean who wants to be publicly ridiculed? Dude I've been following you too, you have a lot of potential...

**Comment by akhilnarang** [comment]
@nakedpwr Okay
