### ISSUE TITLE
Can't apply theme on samsung 9.0

### ISSUE THREAD

**Issue by ReturnAc** [nicholaschum/substratum#193]
Before I flash the 9.0 , I can apply theme normal. But now it appears errors. I saw other people who on samsung 9.0 can apply the theme, what's the reason on my rom?  
![](https://i.imgur.com/DxK0v30.jpg)
![](https://i.imgur.com/RJp2JLM.jpg)
![](https://i.imgur.com/doffAkR.jpg)
![](https://i.imgur.com/xvaMgaM.jpg)

**Comment by Raymonf** [comment]
That theme isn't compatible with Pie

**Comment by ReturnAc** [comment]
@Raymonf No,the theme creator has adapted for Pie...

**Comment by Raymonf** [comment]
There are different versions of One UI.

在 2019年3月12日週二 下午7:26，ReturnAc <notifications@github.com<mailto:notifications@github.com>> 寫道：

@Raymonf<https://github.com/Raymonf> No,the theme creator has adapted for Pie...

**Comment by ReturnAc** [comment]
@Raymonf ok.:cry:
