### ISSUE TITLE
Crashing and updating

### ISSUE THREAD

**Issue by daniel-arrick** [nicholaschum/substratum#194]
Hello I have a Galaxy S7 and purchased Substratum dark theme. 

Apps that are out of date with theme overlays crash and need frequent updating. It's difficult to update though due to every update needing individual permissions check even when no permission changes. Is there a way to batch action update or perhaps auto update? Otherwise I need to explore a new theme engine because of constant maintenance and troubleshooting.

Thanks

**Comment by msfjarvis** [comment]
Not sure what you mean by permission check. On platforms where overlays can be installed without user intervention, Substratum does provide the ability to update overlays in the background after app updates.

**Comment by msfjarvis** [comment]
Stale issue, closing for now.
