### ISSUE TITLE
Substratum Legacy on LOS 16.0 OFFICIAL Scorpio Build with SELINUX seems to be buggy...

### ISSUE THREAD

**Issue by Lennard-Bargfrede** [nicholaschum/substratum#195]
Hey there substratum team,
i am having this error since the last LOS 16 Update. Before that i had run LOS 16 UNOFFICAIL.
I am getting this ERROR for like 5 Overlays out of 20 that i have compiled:

04-01 11:13:10.467  4418  4418 W ziparchive: Unable to open 'path_to_some_overlay_apk': No such file or directory
04-01 11:13:10.467  4418  4418 E id.gms.unstabl: Failed to open APK 'path_to_some_overlay_apk' I/O error
04-01 11:13:10.467  4418  4418 W ResourcesManager: failed to add overlay path path_to_some_overlay_apk
As far as i can see it right now, the problem vanished after i disabled SELINUX on bootup. I have tryed different Themes also - but with the same effect. It seems to be only the google gms overly and the basic Android Overlay (Android System and UI). I am currently running on LOS16 Nighly 30.3.2019 with substratum Legacy Support.

Thanks in advance !

**Comment by Lennard-Bargfrede** [comment]
Ohh, i forgot to add: The apk is actually present in that directory and SELINUX does not enforce as far as i can read the logcat.

**Comment by msfjarvis** [comment]
AOSP is unaffected and your logcat snippet is unhelpful at best so I'm at a loss as to what I can do about this. I'm not keen on working around issues created by ROMs so if this is an actual problem that requires too much intervention, it will most likely not be fixed.

**Comment by Lennard-Bargfrede** [comment]
I dont acually think that it is a problem within the ROM, since its SELINUX and substratum related. Substratum wants to add an Overlay in that path, which does exists in that path and when you disable selinux it still cant access the path(from what i can read in the logcat), and with enabled selinux, you have a laggy as hell android - 3 Sec startup for Gallery and this is on all Apps. Even when you slide right in whatsapp its taking 2secs to do that. After uninstalling the themes it works again.

You dont need to do anything about this - i just wanted to inform that it seems that substratum as some kind of issue with selinux on LOS16 :P. But i dont know for sure if its just for my devices. I can live with this fix on disabling selinux.

**Comment by Lennard-Bargfrede** [comment]
Which Infos do you need ?

**Comment by msfjarvis** [comment]
> Which Infos do you need ?

Well for starters I need your device's name, the Magisk version you're on and an actual logcat, not your interpretation of it.

**Comment by Lennard-Bargfrede** [comment]
Device Name Scorpio
Magisk v18.1
Logcat: https://pastebin.com/0wf8b4q4
This Logcat is with Selinux enabled, i can confirm that it does not work like i thought it would with selinux disabled.

**Comment by msfjarvis** [comment]
> Device Name Scorpio
> Magisk v18.1
> Logcat: https://pastebin.com/0wf8b4q4
> This Logcat is with Selinux enabled, i can confirm that it does not work like i thought it would with selinux disabled.

Nothing really useful in there. Do `/system/app/_com.google.android.gms.SwiftBlack.PixelandAOSP.apk` or `/system/app/_android.SwiftBlack.Livid.PixelandAOSP.apk` exist? Did you reboot after installing/uninstalling either of them?

**Comment by Lennard-Bargfrede** [comment]
Yes those do exist and i always reboot after compiling and even tho after enabling since this issue.
