### ISSUE TITLE
Create repository for F Droid.

### ISSUE THREAD

**Issue by dontreallycodebutwhatever** [nicholaschum/substratum#197]
I understand you've been denied from the F-droid store. Consider following this [guide](https://f-droid.org/en/docs/Setup_an_F-Droid_App_Repo/) to set up your own repo. Additionally, **you don't even need to host it yourself**. See the Guardian Project's [mirror](https://github.com/guardianproject/fdroid-repo) repo on GitHub for an example. 

This will make it a lot easier for individuals who don't want to use the Play Services Framework to keep all their apps updated. 

Thanks for your consideration!

**Comment by msfjarvis** [comment]
Almost every substratum theme requires Google Play Services to validate purchases, so I have no clue how you're going to use substratum without it. If you're going the microG route, use Yalp or the numerous other derivatives for the purpose. I have little to no interest in hosting an F-Droid repository.
