### ISSUE TITLE
Please help me the selected overlay updated with errors

### ISSUE THREAD

**Issue by karimahmadmaoud** [nicholaschum/substratum#198]
I just purchased andromeda and i'm using Android oreo, i followed the whole steps 
And i just keep getting the same problem
the selected overlay updated with errors
Please help me guys i did everything i could to make it work and i failed 😭 I don't want to give it up i really love this app!

**Comment by takarushi** [comment]
@karimahmadmaoud theme supports Oreo?, if yes make sure you're using Oreo overlays

**Comment by karimahmadmaoud** [comment]
Yes definitely its supports oreo 
I have a stock rom oppo f9 
I just need a solution, i really want to make it work

**Comment by takarushi** [comment]
the theme supports Oppo's ColorOS?, i have never seen a theme that supports it

**Comment by karimahmadmaoud** [comment]
What!!! Are you kidding me?? 
I thought that it based on the android version not the os?!
So why did i purchased andromeda??
Anyway Can you tell me how to apply the oreo overlays please

**Comment by takarushi** [comment]
"technically" the theme has to support your OEM skin to work properly, as a example, I can't install a Samsung Oreo overlay in AOSP Oreo and expect it work, in your case you said that Oreo was supported, but you didn't specified which Oreo flavour was supported, like AOSP, Samsung, 1+, etc, if the theme doesn't supports ColorOS won't work, it's not substratum or Andromeda fault, it's just the theme not designed to work with your OEM skin

**Comment by karimahmadmaoud** [comment]
So i will not be able to use substratum like forever?

**Comment by takarushi** [comment]
you're able to use it, but you'll need a theme that let's you theme third-party apps, not system one, because most themes doesn't supports ColorOS

**Comment by karimahmadmaoud** [comment]
I cannot believe that i waste my money on that! 
Why you guys didn't leave a note like its not supported all the oreo models 
Am really really disappointed

**Comment by takarushi** [comment]
it's not substratum's fault, it's just the dev who created the theme not wanting to support ColorOS, blame him, not substratum developers

**Comment by bohrabhijeet** [comment]
A theme not supporting ColorOS shouldn't be a big deal. If ColorOS has in-built themes, use them to theme your system (like Settings) 

However, you can use the theme on Oreo and theme the 3rd party apps supported by the same.

**Comment by karimahmadmaoud** [comment]
Dude let's be honest and clear, there's no theme that supports Oppo color os .. can you believe that?? There is a million supports xiaomi, samsung, even pixel but guess what oppo not listed? Is that even fair
I just purchased the whole thing to use it 
Not rooted not ilegal
I want my money back

**Comment by takarushi** [comment]
it's not our fault, you downloaded a theme that literally doesn't supports your skin, theme devs can select which OEM skin can support and it's their decision

**Comment by karimahmadmaoud** [comment]
@bohrabhijeet can you explain more how i could use it from the oppo themes please??
Is that means that i can use the substratum?
The full overlay?

**Comment by yash-garg** [comment]
You cannot use substratum anyway through oppo's theme store

**Comment by takarushi** [comment]
Oppo Theme store is a different whole thing and it won't use substratum overlays, so don't expect to get working the theme using their theme store

**Comment by karimahmadmaoud** [comment]
@tak1nu dude it supports my android oreo 8.1 
But it doesn't apply the overlays at all

**Comment by takarushi** [comment]
@karimahmadmaoud if you send a log, it would be more easy to determine your "issue"

**Comment by karimahmadmaoud** [comment]
@Yash-Garg okay i already know that
I just need to apply a theme through substratum am fed up !!!!! :(

**Comment by karimahmadmaoud** [comment]
@tak1nu » [com.android.systemui]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout/qs_panel.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@*com.android.systemui:id/qs_background').
» [com.android.systemui]: /data/user/0/projekt.substratum/cache/SubstratumBuilder//res/layout/qs_panel.xml:7: error: Error: No resource found that matches the given name (at 'layout' with value '@*com.android.systemui:layout/qs_footer').
» [com.android.systemui]: Installation of "com.android.systemui" has failed.

**Comment by tak1nu** [comment]
you literally didn't selected your Android version at the top, that's the why you're getting those //res/layout doesn't exist error

**Comment by karimahmadmaoud** [comment]
Dude i swear to jesus i just selected my overlay oreo 8.1 i just keep getting the same problem please help me 😥

**Comment by takarushi** [comment]
if you try theming third-party apps, they get themed? if yes, your theme doesn't supports ColorOS SystemUI

**Comment by karimahmadmaoud** [comment]
Nothing changes at all, i gave up

**Comment by karimahmadmaoud** [comment]
This is exactly my problem but i can't fix it
https://youtu.be/jzEdsuZsyFM

**Comment by gcantoni** [comment]
What's going on here? 

Support -> https://t.me/joinchat/BTodxkJMTTTgYmCfPL7IIA

**Comment by karimahmadmaoud** [comment]
I can't join the support and chat until tomorrow! I just need an immediate response and fix please
