### ISSUE TITLE
App crashes on start after root access is granted

### ISSUE THREAD

**Issue by math-rock** [nicholaschum/substratum#199]
Device: OnePlus3T with Lineage 16 (Pie), root
Latest version of substratum from Play Store

Bug: Crashes on startup

Steps to reproduce:

Method 1:

1. Download app, install
2. Grant root access when prompted immediately after startup
3. App now crashes

Method 2:

1. Download app, install
2. Deny root access at start, pass through tutorial screen and enter main app view
3. Grant root access but do not save permission
4. Close app
5. Open app
6. Deny root access
7. App crashes
8. Restart app, grant root access
9. App crashes permanently again

Flashing one or both rescue zips in latest TWRP did not resolve issue.

**Comment by msfjarvis** [comment]
Going to need a logcat.

**Comment by math-rock** [comment]
Here's the logcat: https://pastebin.com/dYjHhLuH

**Comment by msfjarvis** [comment]
> Here's the logcat: [pastebin.com/dYjHhLuH](https://pastebin.com/dYjHhLuH)

```
05-30 13:08:43.441 E/AndroidRuntime( 1333): Caused by: java.lang.IllegalArgumentException: Magisk version cannot be lesser than 18.0!
```

Magisk is the only supported root method for substratum.
