### ISSUE TITLE
Overlays on a system-as-root android.

### ISSUE THREAD

**Issue by thanuj10** [nicholaschum/substratum#202]
Building and installing themes when a device is system-as-root results in not theming whatsoever after re-booting. These overlays will not even show up in the manager unless you use a workaround(Described below).

This is due to fact that the overlay are getting installed to ```/root/system/app/``` instead of ```/root/system_root/system/app/```

One workaround of doing this manually is moving the overlays from ```/root/system/app/``` to ```/root/system_root/system/app/``` using a file explorer, Then re-booting. After re-booting go into Substratum's overlay manager and enable all the overlays and re-boot system UI.

This is actually not great for 2 reasons because, Once the overlays are installed into ```/root/system/app/``` then they will not be uninstallable, detectable for the Substratum app. Using a file manager to remove these overlays manually is also not possible because it fails to do so.(Any file manager app with root capabilities fail). Moving the files(Cut+Paste) also does not remove those overlays from ```/root/system/app/``` too. So it is as if the overlays are installed 2 times but the overlays in the ```/root/system/app/``` are being hidden by .nomedia file.

One possible solution is to give the Substratum app the capability to detect if the system is using normal root or system-as-root and then change the installation directories accordingly.

>Device tested on - Nokia 6.1 Plus running DotOS/Pixel Experience/Stock ROM all based on Android 9.0 Pie.

**Comment by msfjarvis** [comment]
system-as-root devices cannot remount system as RW because it happens to be the rootfs as well, so the only possible way to theme on them is the Magisk module, which does not present any of problems you're describing.

**Comment by thanuj10** [comment]
Can you link me to the module?

**Comment by msfjarvis** [comment]
The app generates it on the fly. It's simply an installation directory that mounts overlays over system.

**Comment by thanuj10** [comment]
Okay then, Ill close the issue. But it'll be great if you can add an option to detect system-as-root... 

Cheers

**Comment by msfjarvis** [comment]
You're still missing the entire point of what I told you before. There is _nothing_ to detect. When Magisk is installed, the app will simply defer installation to the module because that's the only real way to do things on system-as-root. You _cannot_ mount a system-as-root device's system as RW because it's the rootfs. If you're not using Magisk for root, then you're the one creating problems for yourself and the app cannot fix or "detect" that.

**Comment by thanuj10** [comment]
Im amateur in these root things so please forgive me. But I do use magisk for root access.
