### ISSUE TITLE
Can't apply any theme.

### ISSUE THREAD

**Issue by martincz** [nicholaschum/substratum#34]
Thanks for you good work.
MoKee Rom want use substratum theme engine.
I cherry-pick all changes and compile a new rom, but it not work.
Can you help me slove it?
I don't know what changes I missed?
Here is our source code: https://github.com/MoKee
review page: https://review.mfunz.com/#/q/status:merged

Thank you.

**Comment by martincz** [comment]
![image](http://i.imgur.com/HPNnPIC.jpg)
![image](http://i.imgur.com/43x2Kyz.png)
Always in progress... can't take effect.

**Comment by nathanchance** [comment]
Have you granted Masquerade Superuser permissions?

**Comment by martincz** [comment]
@nathanchance No, but I cherry-picked this commit:
Rewrite Masquerade for UID system ops
http://review.projektsubstratum.com/#/c/249/

**Comment by Myself5** [comment]
@martincz you saw that this commit is WIP, right?

**Comment by martincz** [comment]
@Myself5 So, it not work right?

**Comment by nathanchance** [comment]
@martincz there is a reason that commit is on open, it's not ready for primetime yet. It also needs hooks in Substratum itself so if you aren't building the app from Nick's repo directly, it does nothing.

**Comment by martincz** [comment]
@nathanchance Thanks, I'll try Superuser permissions version.
Btw, Can you add Chinese language support?

**Comment by nicholaschum** [comment]
@martincz Chinese language support is welcome as long as there is a translator that is willing to do it. I may be Chinese, but I would prefer if there would be more eyes than my own on Chinese support.

**Comment by martincz** [comment]
@nicholaschum Good, do you have a [crowdin](https://crowdin.com/) page? 
I'll notify our users to translate, we have many Chinese users :)

**Comment by nicholaschum** [comment]
@martincz I'll be setting up a more userfriendly way of translating soon. We are currently using OneSkyApp where collaborators are manually added (to prevent spammers).

If you have Telegram, please hit me up @nicholaschum. Or you can contact my hangouts at chummydevteam@gmail.com
