### ISSUE TITLE
no x86_64 aapt or aopt

### ISSUE THREAD

**Issue by youling257** [nicholaschum/substratum#52]
copy apk package assets files
$ file /su/aapt
/su/aapt: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=ba7673bc6a50b38e87e1da16b8c07160c2f96086, stripped, with debug_info
$ file /su/aapt86
/su/aapt86: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, BuildID[sha1]=e6b
e62d0d40bb8bfe08026108ca1ac505, stripped, with debug_info
$ file /su/aopt
/su/aopt: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[md5/uuid]=42925f9167639182c56b78c8cc466ddf, stripped, with debug_info
$ file /su/aopt64
/su/aopt64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, BuildID[md5/uuid]=582c21b96272c929eec3b20835a7020a, stripped, with debug_info
$
no x86_64 aapt，x86_64 aopt .

**Comment by youling257** [comment]
android x86_64 lineage os 14.1

**Comment by nicholaschum** [comment]
What is your question?

**Comment by youling257** [comment]
suggest add x86_64 aapt or aopt .

**Comment by nicholaschum** [comment]
https://github.com/substratum/substratum/tree/dev/app/src/main/assets

It is here.

**Comment by youling257** [comment]
yes，aapt: ELF 32-bit LSB shared object, ARM, aapt86: ELF 32-bit LSB shared object, Intel 80386, aopt: ELF 32-bit LSB executable, ARM, aopt64: ELF 64-bit LSB executable, ARM aarch64,  
request ELF 64-bit LSB shared object, x86-64,

**Comment by nicholaschum** [comment]
Does the x86_32 binary not run on 64bit?
