### ISSUE TITLE
Explain Step 5 correctly and with example

### ISSUE THREAD

**Issue by SwapnilSoni1999** [nicholaschum/substratum#54]
As a noob in javascripts.. i cant understand what step 5 is saying, please describe with an example please and the lines you highlighted is maybe wrong.. if not then tell me how to solve this issue.. 
After running app in substratum it shows like 
"This theme's binary does not pass 
  Substratum's integrity verification"
I guess its because of step 5 which i didnt done correctly... 
Needed A helful answer please.

**Comment by KreAch3R** [comment]
Step 5 where? In the template? Because this is the main substratum repo.

Anyway though, if you are building your own theme and you have this error, don't use "instant run" and uninstall everything - reinstall it from scratch, it shouldn't happen because of the changelog.

**Comment by SwapnilSoni1999** [comment]
Yea in theme template.. 
But i dont get that scratch thing.. 
Actuqlly i followed xdatv's tutorial for making theme. Well i will try it again, i posted this issue on xda forums but seems nic sir aint replying ':)

**Comment by SwapnilSoni1999** [comment]
Done, actually i had to change gradle file.. sorry fr disturbance ':)

**Comment by xdevs23** [comment]
@SwapniSoni1999 Wtf

**Comment by xdevs23** [comment]
@xdevs23 Damn this github bot
