### ISSUE TITLE
Make available on F-Droid

### ISSUE THREAD

**Issue by ghost** [nicholaschum/substratum#55]
Users choose to avoid non-free google services. F-Droid is a great option for an app repository for free apps that provides updates.

Please make available either via submitting to the official repository, or hosting your own.

**Comment by Sykopompos** [comment]
Substratum is also available on apkmirror for users to download, will probably be on xda soon as another method and a thing we are discussing from a suggestion is making it available on github so a rom could pull in updates without the play store.
