### ISSUE TITLE
AOPT sources

### ISSUE THREAD

**Issue by arter97** [nicholaschum/substratum#70]
Are you guys planning to release sources for AOPT?

We can do some (pretty noticeable) improvements there.

It'll be my first contribution, if it gets released.

Thanks.

**Comment by nicholaschum** [comment]
Oh hey @arter97. As far as we know, AOPT is open sourced on our Gerrit (very old commit), and a modified version of AAPT (from Google).

We will be looking into publishing it into a different repository very soon. Until then, I will keep this issue tracker open, and tag you when it is available with full commit history intact.

**Comment by arter97** [comment]
That'll be much appreciated.
Thanks!

**Comment by TheCrazyLex** [comment]
Yeah this would be awesome

**Comment by nathanchance** [comment]
And done :) https://github.com/substratum/aopt

@arter97 @TheCrazyLex
