### ISSUE TITLE
Overlay manager: possible minor improvement

### ISSUE THREAD

**Issue by Jertlok** [nicholaschum/substratum#82]
Inside the overlay manager it is possibile to choose the color variants that, for instance, a theme offers. 

Let's take in consideration the values found inside the Android System _voice_:
![image](https://cloud.githubusercontent.com/assets/6817879/24175066/7993959a-0e94-11e7-862f-ba99c6b0c9e8.png)
- System accent
- Background color
- Apps primary color

As soon as an user modifies each value there's no reference to what he actually modified.
**What about appending a little description next to the chosen value?** 

_Example:_
![image](https://cloud.githubusercontent.com/assets/6817879/24175049/6662cca2-0e94-11e7-90a2-b2636d99655d.png)

**Comment by Surge1223** [comment]
That would rob users of the wonderful delight of enlightenment.  No better way to learn than to just try. Typically,  you will have users ask a lot of questions, in cases like this it might be better if they " learn the hard way".  Plus, at some point, they will have to figure out how to use google.  Let's have faith in the ability of others to use Google. I know that's asking a lot, but desperate times call for desperate measures.

**Comment by Sykopompos** [comment]
I don't have any faith in other's ability to use Google.

Right now this is something to look into and come up with a design to do it, every theme is different and the options can be used any way the themer wants to use it (could be completely different options on a different theme)

**Comment by nicholaschum** [comment]
I like the idea

**Comment by Jertlok** [comment]
@Surge1223, i definitely agree with you. People can just get used to what a developers offer but this, talking about Software Engineering, is not the best practice. Developers should always follow the best balance between features and user comprehension.

**Comment by Jertlok** [comment]
@Sykopompos, you are absolutely right in fact, with this little issue, i wanted to show you just a little improvement we can think of. Actually just a graphical user interface improvement which, indeed, may vary.

**Comment by Sykopompos** [comment]
Most likely it will have to be done on the theme side since it can vary so widely so they would have to put the usage name in.

**Comment by nicholaschum** [comment]
I had some thoughts about this and it will need to be done by the themer if they choose to. I am more so thinking about low-DPI devices and how it will just look super cramped if it appends the original spinner text in there.
