### ISSUE TITLE
Inconsistent FAQ (?)

### ISSUE THREAD

**Issue by Jertlok** [nicholaschum/substratum#85]
The _answer four_, relative to the question "Can I use Substratum even if my ROM does not have OMS support?", clearly shows that Substratum needs root in order to work. As far as i know now Substratum uses rootless methods. 
@nicholaschum, what do you think about it?

**Comment by akhilnarang** [comment]
It needs root if you're on a ROM without commits for OMS and rootless support. If the ROM has those commits, then it'll work without root.

**Comment by Jertlok** [comment]
Thanks, you are right. So, i can close this issue.
JFY, i opened it because i am trying to improve the italian translation - there are a lot of mistake.
