### ISSUE TITLE
[FAQ Inconsistency] Possibile outdated answer

### ISSUE THREAD

**Issue by Jertlok** [nicholaschum/substratum#86]
Talking about the [_answer five_](http://translate.projektsubstratum.com/translate/substratum/4/enca-it#605) there is a reference to a _Quick Apply_ tab. I don't see any _Quick Apply_ tab on my end. Does this answer refer to old Substratum processes? 
Thanks in advance.

**Comment by msfjarvis** [comment]
Quick Apply was removed due to lack of actual utility and it being rather unused. For further queries you can join the Telegram chat linked within the app, since issues section on this repository is meant for bugs in the substratum app itself.

**Comment by Jertlok** [comment]
Oh, yes even though there are multiple labels proceeding this way the issues page would get dirty.
Let me join the Telegram channel and close this issue.
Thank you.
