### ISSUE TITLE
Avoid static view

### ISSUE THREAD

**Issue by AllanWang** [nicholaschum/substratum#89]
I took a quick look at the code and I see views like the [SearchView](https://github.com/substratum/substratum/blob/dev/app/src/main/java/projekt/substratum/MainActivity.java#L117) working statically.

There are many ways around this, from simply casting context to MainActivity to call a setter method, or even using EventBus so you don't need a reference at all to change a value.

Might be just me, but the Settings option in the drawer isn't working in v627

**Comment by msfjarvis** [comment]
@AllanWang Settings option is working perfectly here on 627, both with clean install and an upgrade from 621.

**Comment by nicholaschum** [comment]
It is suppressed for a reason. You can do a pull to fix it but the main reason why someone would want to keep avoiding it nowadays is because of Instant Run. We don't work with Instant Run.
